name       : capstone
version    : 4.0.1
release    : 1
source     :
    - https://github.com/aquynh/capstone/archive/4.0.1.tar.gz : 79bbea8dbe466bd7d051e037db5961fdb34f67c9fac5c3471dd105cfb1e05dc7
license    : BSD-3-Clause
component  : programming.library
summary    : Disassembly/disassembler framework
description: |
    Capstone is a disassembly framework with the target of becoming the ultimate disasm engine for binary analysis and reversing in the security community.
setup      : |
    %cmake_ninja -DCAPSTONE_BUILD_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
