name       : capstone
version    : 4.0.2
release    : 2
source     :
    - https://github.com/aquynh/capstone/archive/4.0.2.tar.gz : 7c81d798022f81e7507f1a60d6817f63aa76e489aa4e7055255f21a22f5e526a
license    : BSD-3-Clause
component  : programming.library
homepage   : https://www.capstone-engine.org/
summary    : Disassembly/disassembler framework
description: |
    Capstone is a disassembly framework with the target of becoming the ultimate disasm engine for binary analysis and reversing in the security community.
setup      : |
    %cmake_ninja -DCAPSTONE_BUILD_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
